function pug_attr(t,e,n,f){return e!==!1&&null!=e&&(e||"class"!==t&&"style"!==t)?e===!0?" "+(f?t:t+'="'+t+'"'):("function"==typeof e.toJSON&&(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||e.indexOf('"')===-1)?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"):""}
function pug_attrs(t,r){var a="";for(var s in t)if(pug_has_own_property.call(t,s)){var u=t[s];if("class"===s){u=pug_classes(u),a=pug_attr(s,u,!1,r)+a;continue}"style"===s&&(u=pug_style(u)),a+=pug_attr(s,u,!1,r)}return a}
function pug_classes(s,r){return Array.isArray(s)?pug_classes_array(s,r):s&&"object"==typeof s?pug_classes_object(s):s||""}
function pug_classes_array(r,a){for(var s,e="",u="",c=Array.isArray(a),g=0;g<r.length;g++)s=pug_classes(r[g]),s&&(c&&a[g]&&(s=pug_escape(s)),e=e+u+s,u=" ");return e}
function pug_classes_object(r){var a="",n="";for(var o in r)o&&r[o]&&pug_has_own_property.call(r,o)&&(a=a+n+o,n=" ");return a}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_has_own_property=Object.prototype.hasOwnProperty;
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}
function pug_style(r){if(!r)return"";if("object"==typeof r){var e="",t="";for(var n in r)pug_has_own_property.call(r,n)&&(e=e+t+n+":"+r[n],t=";");return e}return r=""+r,";"===r[r.length-1]?r.slice(0,-1):r}function pugform(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"T:\\electron\\pug\\forms\\form.pug":"#{tag}&attributes(attr)\r\n  if content\r\n    | !{content}\r\n  else if childs\r\n    each child in childs\r\n      | !{child}"};
;var locals_for_with = (locals || {});(function (attr, childs, content, tag) {;pug_debug_line = 1;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
pug_html = pug_html + "\u003C" + (tag) + (pug_attrs(attr, false)) + "\u003E";
;pug_debug_line = 2;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
if (content) {
;pug_debug_line = 3;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
pug_html = pug_html + (null == (pug_interp = content) ? "" : pug_interp);
}
else
if (childs) {
;pug_debug_line = 5;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
// iterate childs
var pug_obj0 = childs;
if ('number' == typeof pug_obj0.length) {

  for (var pug_index0 = 0, pug_length0 = pug_obj0.length; pug_index0 < pug_length0; pug_index0++) {
    var child = pug_obj0[pug_index0];

;pug_debug_line = 6;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
pug_html = pug_html + (null == (pug_interp = child) ? "" : pug_interp);
  }

} else {
  var pug_length0 = 0;
  for (var pug_index0 in pug_obj0) {
    pug_length0++;
    var child = pug_obj0[pug_index0];

;pug_debug_line = 6;pug_debug_filename = "T:\\electron\\pug\\forms\\form.pug";
pug_html = pug_html + (null == (pug_interp = child) ? "" : pug_interp);
  }

}

}
pug_html = pug_html + "\u003C\u002F" + (tag) + "\u003E";}.call(this,"attr" in locals_for_with?locals_for_with.attr:typeof attr!=="undefined"?attr:undefined,"childs" in locals_for_with?locals_for_with.childs:typeof childs!=="undefined"?childs:undefined,"content" in locals_for_with?locals_for_with.content:typeof content!=="undefined"?content:undefined,"tag" in locals_for_with?locals_for_with.tag:typeof tag!=="undefined"?tag:undefined));} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;};
module.exports = pugform;